name: triangle CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    container: <lastwordxin>/homework:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 -m pytest
